// Generated by CoffeeScript 1.8.0
(function() {
  exports.parse = function(str) {
    return str.split('\n').map(JSON.parse);
  };

  exports.stringify = function(rows) {
    return rows.map(JSON.stringify).join('\n');
  };

}).call(this);
