// Generated by CoffeeScript 1.8.0
var Widget, domify, html;

domify = require('domify');

html = '<div>Hello <span class="name"></span>!</div>';

Widget = function() {
  if (!(this instanceof Widget)) {
    return new Widget();
  }
  return this.element = domify(html);
};

Widget.prototype.setName = function(name) {
  return this.element.querySelector('.name').textContent = name;
};

Widget.prototype.appendTo = function(target) {
  return target.appendChild(this.element);
};

module.exports = Widget();
